### PR TITLE
docs(readme): fix typo "bellow"

### PR DESCRIPTION
**Pull request by AndersDJohnson**

### CODE REVIEW

**Comment by nem035** [comment]
Thanks mate 👍

**Comment by oliviaoddo** [comment]
we do not have "below" we have "bellow"

**Comment by oliviaoddo** [comment]
```
// The code bellow would throw a "Must have at least 1 `content` element" error
<Main>
  <MyCoolSidebar sidebar />
</Main>
```

**Comment by nem035** [comment]
Wow, I just realized I misread your change, sorry

**Comment by nem035** [comment]
Will merge, thanks for the contribution!

**Pull request merged**
